on:
  issues:
    types:
      - opened

jobs:
  sayHello:
    runs-on: ubuntu-latest
    steps:
      - uses: dimitar-hristov/foo-probot@v1.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
