on:
  issues:
    types:
      - opened

jobs:
  sayHello:
    runs-on: ubuntu-latest
    steps:
      - uses: dimitar-hristov/bar-probot@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
