on:
  issues:
    types:
      - opened

jobs:
  sayHello:
    runs-on: ubuntu-latest
    steps:
      - run: pwd
      - run: ls -al
      - uses: dimitar-hristov/dockerfile-action-probot@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
